nelmio_api_doc:
    documentation:
        info:
            title: MotolinkerApi
            description: Api do panelu motolinker udostępnia metody do tworzenia bazy danych części samochodowych
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under / except /doc
