nelmio_api_doc:
    documentation:
        info:
            title: MotolinkerApi
            description: Api do panelu motolinker udostępnia metody do tworzenia bazy danych części samochodowych
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^\/((?!_error)(?!doc)(?!_wdt)(?!_profiler).)*$ # Accepts routes under / except /doc /_error /_wdt /_profler
